SO close to getting data, but getting error
Error:  XMLHttpRequest cannot load. No 'Access-Control-Allow-Origin'
header is present on the requested resource. Origin
'http://localhost:9000' is therefore not allowed access.